# --- BEGIN netlify.toml ---
# Конфигурация кэширования для ускорения сборок.
# Мы убрали секцию [build], так как пресет 'netlify-edge' 
# в app.config.ts позволяет Netlify автоматически определять 
# команду сборки и директорию для публикации.

[build.cache]
  # Список путей, которые нужно кэшировать между сборками
  paths = [
    ".vinxi",           # Кэш сборщика Vinxi
    "node_modules",     # Основная папка с установленными зависимостями
    "~/.npm"            # Глобальный кэш npm для еще большего ускорения
  ]

[template.environment]
  # Эта секция остается для переменных окружения шаблона Netlify
# --- END netlify.toml ---